// Interfeys matnlari. uz_cyrl va uz_new — uz dan avtomatik o'giriladi (lib/i18n.tsx).
export const uz = {
  nav_track: "Kuzatish",
  nav_cabinet: "Kabinet",
  // umumiy
  tagline: "Muassasalar ishlab chiqargan mahsulotlar — to'g'ridan-to'g'ri ishlab chiqaruvchidan",
  search_ph: "Mahsulot, masalan: parta, g'isht, choyshab…",
  search: "Qidirish",
  catalog: "Katalog",
  sellers: "Ishlab chiqaruvchilar",
  cart: "Savat",
  track: "Buyurtmani kuzatish",
  cabinet: "Sotuvchi kabineti",
  login: "Kirish",
  logout: "Chiqish",
  all_categories: "Barcha kategoriyalar",
  categories: "Kategoriyalar",
  home: "Bosh sahifa",
  language: "Til",
  see_all: "Barchasini ko'rish",
  sum: "so'm",
  close: "Yopish",
  back: "Orqaga",
  loading: "Yuklanmoqda…",
  error: "Xatolik yuz berdi",
  footer_about: "Davlat muassasalari ishlab chiqarish korxonalarining mahsulotlarini sotish platformasi. Ariza, shartnoma va to'lov — bitta joyda.",
  footer_buyers: "Xaridorlarga",
  footer_sellers: "Muassasalarga",
  // bosh sahifa
  hero_title: "Ishlab chiqaruvchidan to'g'ridan-to'g'ri: mebel, qurilish materiallari, to'qimachilik",
  hero_sub: "Mahsulotni tanlang, ariza yuboring — muassasa shartnomani tasdiqlaydi. To'lov Click, Payme yoki bank o'tkazmasi orqali.",
  hero_cta: "Katalogga o'tish",
  hero_cta2: "Tashkilotlar uchun",
  stat_products: "mahsulot",
  stat_sellers: "ishlab chiqaruvchi muassasa",
  stat_regions: "hudud",
  stat_categories: "kategoriya",
  popular: "Ko'p so'raladigan mahsulotlar",
  schools_title: "Maktab va bog'chalar uchun mebel",
  schools_sub: "Partalar, o'quvchi va o'qituvchi stollari, kutubxona javonlari — ulgurji narxda, shartnoma asosida.",
  build_title: "Qurilish uchun hammasi",
  build_sub: "G'isht, shlakoblok, pustotali plitalar, beton, sheben — zavod narxida.",
  how_title: "Qanday ishlaydi",
  how1_t: "Tanlang", how1_d: "Katalogdan mahsulot va miqdorni tanlang, qoldiq ko'rinib turadi.",
  how2_t: "Ariza yuboring", how2_d: "Jismoniy yoki yuridik shaxs sifatida ma'lumotlaringizni kiriting.",
  how3_t: "Shartnoma", how3_d: "Muassasa arizani tasdiqlaydi, shartnoma PDF va QR-kod bilan tayyor bo'ladi.",
  how4_t: "To'lov va yetkazish", how4_d: "Click, Payme yoki bank o'tkazmasi. Mahsulot yetkaziladi yoki o'zingiz olib ketasiz.",
  b2b_title: "Tashkilotlar va davlat muassasalari uchun",
  b2b_sub: "Yuridik shaxslar uchun shartnoma bank o'tkazmasi (perechisleniye) asosida tuziladi. Hisob-faktura va yuk xati beriladi.",
  b2b_cta: "Ulgurji buyurtma berish",
  sellers_title: "Ishlab chiqaruvchi muassasalar",
  products_n: "{n} ta mahsulot",
  // mahsulot
  price_on_request: "Narxi kelishiladi",
  per_unit: "/ {unit}",
  in_stock: "Mavjud: {n} {unit}",
  made_to_order: "Buyurtma asosida",
  out_of_stock: "Qolmagan",
  add_to_cart: "Savatga",
  in_cart: "Savatda",
  buy_now: "Ariza berish",
  qty: "Miqdor",
  min_order: "Minimal buyurtma: {n}",
  delivery_yes: "Yetkazib berish bor",
  delivery_no: "Faqat olib ketish",
  lead_days: "Tayyorlash: {n} kun",
  produced_at: "Ishlab chiqarilgan joy",
  specs: "Xususiyatlari",
  similar: "O'xshash mahsulotlar",
  same_seller: "Shu muassasaning boshqa mahsulotlari",
  seller: "Ishlab chiqaruvchi",
  sku: "Artikul",
  daily_capacity: "Kunlik quvvat",
  go_to_cart: "Savatga o'tish",
  price_note: "Narxlar so'mda. Yakuniy narx shartnomada qayd etiladi.",
  // katalog
  filters: "Filtrlar",
  reset: "Tozalash",
  sort: "Saralash",
  sort_popular: "Ommabop",
  sort_price_asc: "Arzonroq",
  sort_price_desc: "Qimmatroq",
  sort_new: "Yangi",
  price_from: "dan",
  price_to: "gacha",
  price: "Narx",
  only_in_stock: "Faqat mavjudlari",
  with_delivery: "Yetkazib berish bilan",
  only_priced: "Narxi ko'rsatilgan",
  region: "Hudud",
  found: "{n} ta mahsulot topildi",
  nothing_found: "Hech narsa topilmadi. Filtrlarni o'zgartirib ko'ring.",
  show_results: "Natijalarni ko'rsatish",
  prev: "Oldingi",
  next: "Keyingi",
  // savat
  cart_empty: "Savat bo'sh",
  cart_empty_sub: "Katalogdan kerakli mahsulotlarni tanlang.",
  go_shopping: "Xarid qilish",
  separate_note: "Har bir muassasa bilan alohida shartnoma tuziladi — savat muassasalar bo'yicha guruhlangan.",
  subtotal: "Oraliq summa",
  total: "Jami",
  checkout: "Rasmiylashtirish",
  remove: "O'chirish",
  items_n: "{n} ta mahsulot",
  priced_later: "Narxi kelishiladigan mahsulotlar narxini muassasa shartnomada belgilaydi.",
  // rasmiylashtirish
  checkout_title: "Arizani rasmiylashtirish",
  buyer_type: "Xaridor turi",
  individual: "Jismoniy shaxs",
  company: "Yuridik shaxs / tashkilot",
  full_name: "F.I.Sh.",
  pinfl: "JShShIR (14 raqam)",
  passport: "Pasport seriya va raqami",
  phone: "Telefon",
  email: "E-pochta",
  address: "Manzil",
  company_name: "Tashkilot nomi",
  inn: "STIR",
  director: "Rahbar F.I.Sh.",
  bank_name: "Bank nomi",
  bank_account: "Hisob raqami",
  mfo: "MFO",
  payment_method: "To'lov usuli",
  pay_click: "Click",
  pay_payme: "Payme",
  pay_bank: "Bank o'tkazmasi",
  pay_online_note: "Shartnoma tasdiqlangach, onlayn to'lov havolasi chiqadi.",
  pay_bank_note: "Shartnomadagi rekvizitlar bo'yicha pul o'tkaziladi (perechisleniye).",
  delivery: "Yetkazib berish",
  pickup: "O'zim olib ketaman",
  delivery_to: "Manzilga yetkazish",
  delivery_address: "Yetkazish manzili",
  comment: "Izoh",
  contract_lang: "Shartnoma tili",
  submit: "Ariza yuborish",
  agree: "Ariza yuborish orqali ommaviy oferta va shartnoma shartlariga rozilik bildirasiz.",
  required: "Majburiy maydon",
  success_title: "Arizangiz qabul qilindi!",
  success_sub: "Muassasa arizani ko'rib chiqib, shartnoma tuzadi. Holatni quyidagi havola orqali kuzating — ariza raqami va telefon orqali ham topish mumkin.",
  app_number: "Ariza raqami",
  view_order: "Arizani ko'rish",
  your_data: "Ma'lumotlaringiz",
  order_summary: "Buyurtma",
  // ariza holati
  order_title: "Ariza {n}",
  st_new: "Yangi",
  st_review: "Ko'rib chiqilmoqda",
  st_contract: "Shartnoma tuzildi",
  st_rejected: "Rad etildi",
  st_cancelled: "Bekor qilindi",
  c_active: "To'lov kutilmoqda",
  c_paid: "To'langan",
  c_shipped: "Jo'natilgan",
  c_done: "Yakunlangan",
  c_cancelled: "Bekor qilingan",
  contract: "Shartnoma",
  download_pdf: "Shartnomani yuklab olish (PDF)",
  open_pdf: "Shartnomani ochish",
  pay_now: "To'lash",
  pay_with: "{m} orqali to'lash",
  paid: "To'langan",
  due: "To'lanishi kerak",
  grand_total: "Umumiy summa",
  bank_title: "To'lov rekvizitlari",
  bank_hint: "To'lov topshiriqnomasida shartnoma raqamini ko'rsating.",
  waiting_seller: "Muassasa arizangizni ko'rib chiqmoqda. Shartnoma tayyor bo'lgach, shu sahifada paydo bo'ladi.",
  seller_comment: "Muassasa izohi",
  history: "Tarix",
  cancel_order: "Arizani bekor qilish",
  track_title: "Buyurtmani kuzatish",
  track_sub: "Ariza raqami va telefon raqamingizni kiriting.",
  order_number: "Ariza raqami",
  find: "Topish",
  not_found: "Topilmadi. Ma'lumotlarni tekshiring.",
  via_agent: "{a} orqali rasmiylashtirilgan",
  delivery_cost: "Yetkazib berish",
  // tekshirish
  verify_title: "Shartnomani tekshirish",
  verify_ok: "Shartnoma haqiqiy",
  verify_bad: "Shartnoma topilmadi",
  contract_no: "Shartnoma raqami",
  date: "Sana",
  buyer: "Xaridor",
  amount: "Summa",
  // demo
  demo: "Demo",
  demo_title: "Demo to'lov sahifasi",
  demo_note: "Click/Payme merchant kalitlari ulanmaguncha to'lov demo rejimda ishlaydi. Haqiqiy pul yechilmaydi.",
  demo_btn: "To'lovni tasdiqlash (Demo)",
  demo_done: "To'lov qabul qilindi (Demo)",
  // kabinet
  dashboard: "Boshqaruv",
  my_products: "Mahsulotlarim",
  applications: "Arizalar",
  contracts: "Shartnomalar",
  general_catalog: "Umumiy katalog",
  profile: "Profil",
  username: "Login",
  password: "Parol",
  sign_in: "Kirish",
  wrong_login: "Login yoki parol noto'g'ri",
  cabinet_login_sub: "Muassasalar uchun alohida login va parol beriladi.",
  new_apps: "Yangi arizalar",
  active_contracts: "Faol shartnomalar",
  month_revenue: "Shu oy shartnomalar",
  receivable: "Debitorlik",
  out_of_stock_n: "Qoldig'i tugagan",
  recent_apps: "So'nggi arizalar",
  top_products: "Eng ko'p sotilganlar",
  add_product: "Mahsulot qo'shish",
  edit: "Tahrirlash",
  save: "Saqlash",
  cancel: "Bekor qilish",
  name: "Nomi",
  spec: "Xususiyati (o'lcham, material)",
  description: "Tavsif",
  category: "Kategoriya",
  unit: "O'lchov birligi",
  stock: "Qoldiq",
  stock_hint: "Bo'sh qoldirilsa — buyurtma asosida",
  reserved: "Band",
  available: "Mavjud",
  active: "Faol",
  hidden: "Yashirin",
  image: "Rasm",
  upload_image: "Rasm yuklash",
  tr_hint: "Faqat o'zbekcha (lotin) yozsangiz ham bo'ladi — kirill va yangi alifbo avtomatik to'ldiriladi. Boshqa tillar bo'sh bo'lsa o'zbekcha ko'rsatiladi.",
  confirm: "Tasdiqlash va shartnoma tuzish",
  reject: "Rad etish",
  reject_reason: "Rad etish sababi",
  review: "Ko'rib chiqishga olish",
  prepayment: "Oldindan to'lov, %",
  payment_days: "To'lov muddati (bank kuni)",
  delivery_days: "Yetkazish muddati (kun)",
  register_payment: "To'lovni qayd etish",
  document_no: "To'lov topshiriqnomasi №",
  ship: "Jo'natildi",
  complete: "Yakunlash",
  cancel_contract: "Shartnomani bekor qilish",
  regenerate: "PDF ni qayta yaratish",
  pay_link: "To'lov havolasi",
  copy: "Nusxa olish",
  copied: "Nusxa olindi",
  agent_title: "Umumiy katalog va qoldiqlar",
  agent_sub: "Barcha muassasalar mahsulotlari. Xaridorga boshqa muassasa mahsulotini taklif qilib, shartnoma chiqarishingiz mumkin — shartnoma mahsulot egasi nomidan tuziladi.",
  owner: "Egasi",
  add_to_deal: "Qo'shish",
  deal: "Shartnoma savati",
  create_deal: "Shartnoma chiqarish",
  deal_note: "Har bir mahsulot egasi bilan alohida shartnoma tuziladi. Siz vositachi sifatida ko'rsatilasiz.",
  deal_done: "Shartnoma(lar) tuzildi",
  scope_all: "Hammasi",
  scope_own: "Menga kelgan",
  scope_agent: "Men rasmiylashtirgan",
  actions: "Amallar",
  status: "Holat",
  created: "Yaratilgan",
  profile_title: "Muassasa profili",
  requisites: "Shartnoma rekvizitlari",
  legal_name: "Rasmiy nomi (shartnomada)",
  treasury: "G'aznachilik shaxsiy hisob raqami",
  change_password: "Parolni o'zgartirish",
  old_password: "Joriy parol",
  new_password: "Yangi parol",
  saved: "Saqlandi",
  operator: "Operator",
  search_orders: "Raqam, xaridor, telefon…",
  no_data: "Ma'lumot yo'q",
  all: "Hammasi",
  items: "Mahsulotlar",
  pcs: "dona",
  price_per: "Narx (birlik)",
  view: "Ko'rish",
  agent: "Vositachi",
  notes: "Ichki izoh",
  payments: "To'lovlar",
  buyer_info: "Xaridor ma'lumotlari",
  set_price: "Narxni kiriting",
  confirm_q: "Ishonchingiz komilmi?",
  published: "Saytda ko'rinadi",
};

export type Dict = typeof uz;
type Partial = { [K in keyof Dict]: string };

export const ru: Partial = {
  nav_track: "Статус",
  nav_cabinet: "Кабинет",
  tagline: "Продукция производственных учреждений — напрямую от производителя",
  search_ph: "Товар, например: парта, кирпич, простыня…",
  search: "Найти",
  catalog: "Каталог",
  sellers: "Производители",
  cart: "Корзина",
  track: "Отследить заказ",
  cabinet: "Кабинет продавца",
  login: "Войти",
  logout: "Выйти",
  all_categories: "Все категории",
  categories: "Категории",
  home: "Главная",
  language: "Язык",
  see_all: "Смотреть все",
  sum: "сум",
  close: "Закрыть",
  back: "Назад",
  loading: "Загрузка…",
  error: "Произошла ошибка",
  footer_about: "Платформа продажи продукции производственных предприятий государственных учреждений. Заявка, договор и оплата — в одном месте.",
  footer_buyers: "Покупателям",
  footer_sellers: "Учреждениям",
  hero_title: "Напрямую от производителя: мебель, стройматериалы, текстиль",
  hero_sub: "Выберите товар и отправьте заявку — учреждение подтвердит договор. Оплата через Click, Payme или банковским перечислением.",
  hero_cta: "Перейти в каталог",
  hero_cta2: "Для организаций",
  stat_products: "товаров",
  stat_sellers: "учреждений-производителей",
  stat_regions: "регионов",
  stat_categories: "категорий",
  popular: "Часто заказывают",
  schools_title: "Мебель для школ и детсадов",
  schools_sub: "Парты, столы для учеников и учителей, библиотечные стеллажи — оптом, по договору.",
  build_title: "Всё для стройки",
  build_sub: "Кирпич, шлакоблок, пустотные плиты, бетон, щебень — по заводской цене.",
  how_title: "Как это работает",
  how1_t: "Выберите", how1_d: "Выберите товар и количество — остатки видны сразу.",
  how2_t: "Отправьте заявку", how2_d: "Укажите данные как физическое или юридическое лицо.",
  how3_t: "Договор", how3_d: "Учреждение подтверждает заявку, договор готов в PDF с QR-кодом.",
  how4_t: "Оплата и доставка", how4_d: "Click, Payme или перечисление. Доставка или самовывоз.",
  b2b_title: "Для организаций и госучреждений",
  b2b_sub: "Для юридических лиц договор заключается с оплатой перечислением. Выдаются счёт-фактура и накладная.",
  b2b_cta: "Оптовый заказ",
  sellers_title: "Учреждения-производители",
  products_n: "{n} товаров",
  price_on_request: "Цена договорная",
  per_unit: "/ {unit}",
  in_stock: "В наличии: {n} {unit}",
  made_to_order: "Под заказ",
  out_of_stock: "Нет в наличии",
  add_to_cart: "В корзину",
  in_cart: "В корзине",
  buy_now: "Оформить заявку",
  qty: "Количество",
  min_order: "Мин. заказ: {n}",
  delivery_yes: "Есть доставка",
  delivery_no: "Только самовывоз",
  lead_days: "Изготовление: {n} дн.",
  produced_at: "Место производства",
  specs: "Характеристики",
  similar: "Похожие товары",
  same_seller: "Другие товары учреждения",
  seller: "Производитель",
  sku: "Артикул",
  daily_capacity: "Мощность в сутки",
  go_to_cart: "Перейти в корзину",
  price_note: "Цены в сумах. Итоговая цена фиксируется в договоре.",
  filters: "Фильтры",
  reset: "Сбросить",
  sort: "Сортировка",
  sort_popular: "Популярные",
  sort_price_asc: "Дешевле",
  sort_price_desc: "Дороже",
  sort_new: "Новые",
  price_from: "от",
  price_to: "до",
  price: "Цена",
  only_in_stock: "Только в наличии",
  with_delivery: "С доставкой",
  only_priced: "С указанной ценой",
  region: "Регион",
  found: "Найдено товаров: {n}",
  nothing_found: "Ничего не найдено. Измените фильтры.",
  show_results: "Показать",
  prev: "Назад",
  next: "Далее",
  cart_empty: "Корзина пуста",
  cart_empty_sub: "Выберите товары в каталоге.",
  go_shopping: "За покупками",
  separate_note: "С каждым учреждением заключается отдельный договор — корзина сгруппирована по учреждениям.",
  subtotal: "Промежуточный итог",
  total: "Итого",
  checkout: "Оформить",
  remove: "Удалить",
  items_n: "{n} товаров",
  priced_later: "Цену на договорные товары учреждение укажет в договоре.",
  checkout_title: "Оформление заявки",
  buyer_type: "Тип покупателя",
  individual: "Физическое лицо",
  company: "Юридическое лицо / организация",
  full_name: "Ф.И.О.",
  pinfl: "ПИНФЛ (14 цифр)",
  passport: "Серия и номер паспорта",
  phone: "Телефон",
  email: "E-mail",
  address: "Адрес",
  company_name: "Название организации",
  inn: "ИНН",
  director: "Ф.И.О. руководителя",
  bank_name: "Банк",
  bank_account: "Расчётный счёт",
  mfo: "МФО",
  payment_method: "Способ оплаты",
  pay_click: "Click",
  pay_payme: "Payme",
  pay_bank: "Перечисление",
  pay_online_note: "После подтверждения договора появится ссылка на онлайн-оплату.",
  pay_bank_note: "Оплата перечислением по реквизитам договора.",
  delivery: "Доставка",
  pickup: "Самовывоз",
  delivery_to: "Доставка по адресу",
  delivery_address: "Адрес доставки",
  comment: "Комментарий",
  contract_lang: "Язык договора",
  submit: "Отправить заявку",
  agree: "Отправляя заявку, вы соглашаетесь с публичной офертой и условиями договора.",
  required: "Обязательное поле",
  success_title: "Заявка принята!",
  success_sub: "Учреждение рассмотрит заявку и оформит договор. Следите за статусом по ссылке — найти заявку можно и по номеру и телефону.",
  app_number: "Номер заявки",
  view_order: "Открыть заявку",
  your_data: "Ваши данные",
  order_summary: "Заказ",
  order_title: "Заявка {n}",
  st_new: "Новая",
  st_review: "На рассмотрении",
  st_contract: "Договор заключён",
  st_rejected: "Отклонена",
  st_cancelled: "Отменена",
  c_active: "Ожидает оплаты",
  c_paid: "Оплачен",
  c_shipped: "Отгружен",
  c_done: "Завершён",
  c_cancelled: "Отменён",
  contract: "Договор",
  download_pdf: "Скачать договор (PDF)",
  open_pdf: "Открыть договор",
  pay_now: "Оплатить",
  pay_with: "Оплатить через {m}",
  paid: "Оплачено",
  due: "К оплате",
  grand_total: "Общая сумма",
  bank_title: "Реквизиты для оплаты",
  bank_hint: "Укажите номер договора в платёжном поручении.",
  waiting_seller: "Учреждение рассматривает заявку. Договор появится на этой странице.",
  seller_comment: "Комментарий учреждения",
  history: "История",
  cancel_order: "Отменить заявку",
  track_title: "Отслеживание заказа",
  track_sub: "Введите номер заявки и телефон.",
  order_number: "Номер заявки",
  find: "Найти",
  not_found: "Не найдено. Проверьте данные.",
  via_agent: "Оформлено через {a}",
  delivery_cost: "Доставка",
  verify_title: "Проверка договора",
  verify_ok: "Договор действителен",
  verify_bad: "Договор не найден",
  contract_no: "Номер договора",
  date: "Дата",
  buyer: "Покупатель",
  amount: "Сумма",
  demo: "Демо",
  demo_title: "Демо-страница оплаты",
  demo_note: "Пока не подключены ключи Click/Payme, оплата работает в демо-режиме. Реальные деньги не списываются.",
  demo_btn: "Подтвердить оплату (Демо)",
  demo_done: "Оплата принята (Демо)",
  dashboard: "Панель",
  my_products: "Мои товары",
  applications: "Заявки",
  contracts: "Договоры",
  general_catalog: "Общий каталог",
  profile: "Профиль",
  username: "Логин",
  password: "Пароль",
  sign_in: "Войти",
  wrong_login: "Неверный логин или пароль",
  cabinet_login_sub: "Каждому учреждению выдаётся отдельный логин и пароль.",
  new_apps: "Новые заявки",
  active_contracts: "Активные договоры",
  month_revenue: "Договоры за месяц",
  receivable: "Дебиторка",
  out_of_stock_n: "Закончились",
  recent_apps: "Последние заявки",
  top_products: "Лидеры продаж",
  add_product: "Добавить товар",
  edit: "Изменить",
  save: "Сохранить",
  cancel: "Отмена",
  name: "Название",
  spec: "Характеристика (размер, материал)",
  description: "Описание",
  category: "Категория",
  unit: "Ед. измерения",
  stock: "Остаток",
  stock_hint: "Пусто — под заказ",
  reserved: "Резерв",
  available: "Доступно",
  active: "Активен",
  hidden: "Скрыт",
  image: "Фото",
  upload_image: "Загрузить фото",
  tr_hint: "Достаточно заполнить по-узбекски (латиница) — кириллица и новый алфавит заполнятся автоматически. Пустые языки показываются по-узбекски.",
  confirm: "Подтвердить и заключить договор",
  reject: "Отклонить",
  reject_reason: "Причина отказа",
  review: "Взять в работу",
  prepayment: "Предоплата, %",
  payment_days: "Срок оплаты (банк. дней)",
  delivery_days: "Срок поставки (дней)",
  register_payment: "Отметить оплату",
  document_no: "№ платёжного поручения",
  ship: "Отгружено",
  complete: "Завершить",
  cancel_contract: "Отменить договор",
  regenerate: "Пересоздать PDF",
  pay_link: "Ссылка на оплату",
  copy: "Копировать",
  copied: "Скопировано",
  agent_title: "Общий каталог и остатки",
  agent_sub: "Товары всех учреждений. Можно предложить покупателю товар другого учреждения и оформить договор — он заключается от имени владельца товара.",
  owner: "Владелец",
  add_to_deal: "Добавить",
  deal: "Корзина договора",
  create_deal: "Оформить договор",
  deal_note: "С каждым владельцем товара заключается отдельный договор. Вы указываетесь как посредник.",
  deal_done: "Договор(ы) оформлены",
  scope_all: "Все",
  scope_own: "Входящие",
  scope_agent: "Оформленные мной",
  actions: "Действия",
  status: "Статус",
  created: "Создана",
  profile_title: "Профиль учреждения",
  requisites: "Реквизиты для договора",
  legal_name: "Официальное название (в договоре)",
  treasury: "Лицевой счёт казначейства",
  change_password: "Сменить пароль",
  old_password: "Текущий пароль",
  new_password: "Новый пароль",
  saved: "Сохранено",
  operator: "Оператор",
  search_orders: "Номер, покупатель, телефон…",
  no_data: "Нет данных",
  all: "Все",
  items: "Товары",
  pcs: "шт",
  price_per: "Цена (ед.)",
  view: "Открыть",
  agent: "Посредник",
  notes: "Внутренняя заметка",
  payments: "Платежи",
  buyer_info: "Данные покупателя",
  set_price: "Укажите цену",
  confirm_q: "Вы уверены?",
  published: "Виден на сайте",
};

export const en: Partial = {
  nav_track: "Track",
  nav_cabinet: "Cabinet",
  tagline: "Goods made by state production facilities — direct from the manufacturer",
  search_ph: "Product, e.g. school desk, brick, bed sheet…",
  search: "Search",
  catalog: "Catalogue",
  sellers: "Manufacturers",
  cart: "Cart",
  track: "Track order",
  cabinet: "Seller cabinet",
  login: "Sign in",
  logout: "Sign out",
  all_categories: "All categories",
  categories: "Categories",
  home: "Home",
  language: "Language",
  see_all: "See all",
  sum: "UZS",
  close: "Close",
  back: "Back",
  loading: "Loading…",
  error: "Something went wrong",
  footer_about: "A marketplace for goods produced by state institutions' production facilities. Application, contract and payment in one place.",
  footer_buyers: "For buyers",
  footer_sellers: "For institutions",
  hero_title: "Direct from the manufacturer: furniture, building materials, textiles",
  hero_sub: "Choose products and send an application — the institution confirms the contract. Pay with Click, Payme or bank transfer.",
  hero_cta: "Browse catalogue",
  hero_cta2: "For organisations",
  stat_products: "products",
  stat_sellers: "manufacturing institutions",
  stat_regions: "regions",
  stat_categories: "categories",
  popular: "Popular products",
  schools_title: "Furniture for schools and kindergartens",
  schools_sub: "School desks, student and teacher tables, library shelving — wholesale, under contract.",
  build_title: "Everything for construction",
  build_sub: "Bricks, cinder blocks, hollow-core slabs, concrete, crushed stone — at factory prices.",
  how_title: "How it works",
  how1_t: "Choose", how1_d: "Pick products and quantities — stock levels are shown.",
  how2_t: "Apply", how2_d: "Enter your details as an individual or a legal entity.",
  how3_t: "Contract", how3_d: "The institution confirms; the contract is ready as a PDF with a QR code.",
  how4_t: "Pay & receive", how4_d: "Click, Payme or bank transfer. Delivery or pick-up.",
  b2b_title: "For organisations and public bodies",
  b2b_sub: "Legal entities contract with payment by bank transfer. An invoice and waybill are issued.",
  b2b_cta: "Place a bulk order",
  sellers_title: "Manufacturing institutions",
  products_n: "{n} products",
  price_on_request: "Price on request",
  per_unit: "/ {unit}",
  in_stock: "In stock: {n} {unit}",
  made_to_order: "Made to order",
  out_of_stock: "Out of stock",
  add_to_cart: "Add to cart",
  in_cart: "In cart",
  buy_now: "Apply now",
  qty: "Quantity",
  min_order: "Min. order: {n}",
  delivery_yes: "Delivery available",
  delivery_no: "Pick-up only",
  lead_days: "Lead time: {n} days",
  produced_at: "Made in",
  specs: "Specifications",
  similar: "Similar products",
  same_seller: "More from this institution",
  seller: "Manufacturer",
  sku: "SKU",
  daily_capacity: "Daily capacity",
  go_to_cart: "Go to cart",
  price_note: "Prices in UZS. The final price is fixed in the contract.",
  filters: "Filters",
  reset: "Reset",
  sort: "Sort",
  sort_popular: "Popular",
  sort_price_asc: "Price: low to high",
  sort_price_desc: "Price: high to low",
  sort_new: "Newest",
  price_from: "from",
  price_to: "to",
  price: "Price",
  only_in_stock: "In stock only",
  with_delivery: "With delivery",
  only_priced: "With price",
  region: "Region",
  found: "{n} products found",
  nothing_found: "Nothing found. Try changing the filters.",
  show_results: "Show results",
  prev: "Previous",
  next: "Next",
  cart_empty: "Your cart is empty",
  cart_empty_sub: "Pick products from the catalogue.",
  go_shopping: "Start shopping",
  separate_note: "A separate contract is made with each institution — the cart is grouped by institution.",
  subtotal: "Subtotal",
  total: "Total",
  checkout: "Checkout",
  remove: "Remove",
  items_n: "{n} items",
  priced_later: "For price-on-request items the institution sets the price in the contract.",
  checkout_title: "Application",
  buyer_type: "Buyer type",
  individual: "Individual",
  company: "Legal entity / organisation",
  full_name: "Full name",
  pinfl: "PINFL (14 digits)",
  passport: "Passport series and number",
  phone: "Phone",
  email: "Email",
  address: "Address",
  company_name: "Organisation name",
  inn: "TIN",
  director: "Head's full name",
  bank_name: "Bank",
  bank_account: "Account number",
  mfo: "MFO",
  payment_method: "Payment method",
  pay_click: "Click",
  pay_payme: "Payme",
  pay_bank: "Bank transfer",
  pay_online_note: "An online payment link appears once the contract is confirmed.",
  pay_bank_note: "Transfer to the bank details stated in the contract.",
  delivery: "Delivery",
  pickup: "I'll pick it up",
  delivery_to: "Deliver to address",
  delivery_address: "Delivery address",
  comment: "Comment",
  contract_lang: "Contract language",
  submit: "Send application",
  agree: "By sending the application you accept the public offer and contract terms.",
  required: "Required",
  success_title: "Application received!",
  success_sub: "The institution will review it and issue a contract. Track the status via the link — you can also find it by number and phone.",
  app_number: "Application No.",
  view_order: "Open application",
  your_data: "Your details",
  order_summary: "Order",
  order_title: "Application {n}",
  st_new: "New",
  st_review: "Under review",
  st_contract: "Contract signed",
  st_rejected: "Rejected",
  st_cancelled: "Cancelled",
  c_active: "Awaiting payment",
  c_paid: "Paid",
  c_shipped: "Shipped",
  c_done: "Completed",
  c_cancelled: "Cancelled",
  contract: "Contract",
  download_pdf: "Download contract (PDF)",
  open_pdf: "Open contract",
  pay_now: "Pay",
  pay_with: "Pay with {m}",
  paid: "Paid",
  due: "Amount due",
  grand_total: "Grand total",
  bank_title: "Payment details",
  bank_hint: "Quote the contract number in the payment order.",
  waiting_seller: "The institution is reviewing your application. The contract will appear here.",
  seller_comment: "Institution's comment",
  history: "History",
  cancel_order: "Cancel application",
  track_title: "Track your order",
  track_sub: "Enter the application number and your phone.",
  order_number: "Application No.",
  find: "Find",
  not_found: "Not found. Check your details.",
  via_agent: "Issued via {a}",
  delivery_cost: "Delivery",
  verify_title: "Contract verification",
  verify_ok: "Contract is valid",
  verify_bad: "Contract not found",
  contract_no: "Contract No.",
  date: "Date",
  buyer: "Buyer",
  amount: "Amount",
  demo: "Demo",
  demo_title: "Demo payment page",
  demo_note: "Until Click/Payme merchant keys are connected, payments run in demo mode. No real money is charged.",
  demo_btn: "Confirm payment (Demo)",
  demo_done: "Payment received (Demo)",
  dashboard: "Dashboard",
  my_products: "My products",
  applications: "Applications",
  contracts: "Contracts",
  general_catalog: "Shared catalogue",
  profile: "Profile",
  username: "Login",
  password: "Password",
  sign_in: "Sign in",
  wrong_login: "Wrong login or password",
  cabinet_login_sub: "Each institution receives its own login and password.",
  new_apps: "New applications",
  active_contracts: "Active contracts",
  month_revenue: "Contracts this month",
  receivable: "Receivables",
  out_of_stock_n: "Out of stock",
  recent_apps: "Recent applications",
  top_products: "Best sellers",
  add_product: "Add product",
  edit: "Edit",
  save: "Save",
  cancel: "Cancel",
  name: "Name",
  spec: "Specification (size, material)",
  description: "Description",
  category: "Category",
  unit: "Unit",
  stock: "Stock",
  stock_hint: "Leave empty for made-to-order",
  reserved: "Reserved",
  available: "Available",
  active: "Active",
  hidden: "Hidden",
  image: "Photo",
  upload_image: "Upload photo",
  tr_hint: "Uzbek (Latin) is enough — Cyrillic and the new alphabet are filled automatically. Empty languages fall back to Uzbek.",
  confirm: "Confirm and create contract",
  reject: "Reject",
  reject_reason: "Reason",
  review: "Start review",
  prepayment: "Prepayment, %",
  payment_days: "Payment term (bank days)",
  delivery_days: "Delivery term (days)",
  register_payment: "Record payment",
  document_no: "Payment order No.",
  ship: "Shipped",
  complete: "Complete",
  cancel_contract: "Cancel contract",
  regenerate: "Regenerate PDF",
  pay_link: "Payment link",
  copy: "Copy",
  copied: "Copied",
  agent_title: "Shared catalogue & stock",
  agent_sub: "Products of all institutions. Offer a buyer another institution's product and issue a contract — it is made in the product owner's name.",
  owner: "Owner",
  add_to_deal: "Add",
  deal: "Contract basket",
  create_deal: "Issue contract",
  deal_note: "A separate contract is made with each product owner. You are recorded as the intermediary.",
  deal_done: "Contract(s) issued",
  scope_all: "All",
  scope_own: "Incoming",
  scope_agent: "Issued by me",
  actions: "Actions",
  status: "Status",
  created: "Created",
  profile_title: "Institution profile",
  requisites: "Contract details",
  legal_name: "Official name (in contract)",
  treasury: "Treasury personal account",
  change_password: "Change password",
  old_password: "Current password",
  new_password: "New password",
  saved: "Saved",
  operator: "Operator",
  search_orders: "Number, buyer, phone…",
  no_data: "No data",
  all: "All",
  items: "Items",
  pcs: "pcs",
  price_per: "Unit price",
  view: "Open",
  agent: "Intermediary",
  notes: "Internal note",
  payments: "Payments",
  buyer_info: "Buyer details",
  set_price: "Enter price",
  confirm_q: "Are you sure?",
  published: "Visible on site",
};

export const kaa: Partial = {
  nav_track: "Baqlaw",
  nav_cabinet: "Kabinet",
  tagline: "Mekemeler islep shıǵarǵan ónimler — tikkeley óndiriwshiden",
  search_ph: "Ónim, mısalı: parta, gerbish, shoyshap…",
  search: "Izlew",
  catalog: "Katalog",
  sellers: "Óndiriwshiler",
  cart: "Sebet",
  track: "Buyırtpanı baqlaw",
  cabinet: "Satıwshı kabineti",
  login: "Kiriw",
  logout: "Shıǵıw",
  all_categories: "Barlıq kategoriyalar",
  categories: "Kategoriyalar",
  home: "Bas bet",
  language: "Til",
  see_all: "Barlıǵın kóriw",
  sum: "sum",
  close: "Jabıw",
  back: "Artqa",
  loading: "Júklenbekte…",
  error: "Qátelik júz berdi",
  footer_about: "Mámleketlik mekemelerdiń óndiris kárxanaları ónimlerin satıw platforması. Arza, shártnama hám tólem — bir jerde.",
  footer_buyers: "Satıp alıwshılarǵa",
  footer_sellers: "Mekemelerge",
  hero_title: "Tikkeley óndiriwshiden: mebel, qurılıs materialları, toqımashılıq",
  hero_sub: "Ónimdi saylań, arza jiberiń — mekeme shártnamanı tastıyıqlaydı. Tólem Click, Payme yamasa bank ótkeriwi arqalı.",
  hero_cta: "Katalogqa ótiw",
  hero_cta2: "Shólkemler ushın",
  stat_products: "ónim",
  stat_sellers: "óndiriwshi mekeme",
  stat_regions: "aymaq",
  stat_categories: "kategoriya",
  popular: "Kóp soralatuǵın ónimler",
  schools_title: "Mektep hám baqshalar ushın mebel",
  schools_sub: "Partalar, oqıwshı hám muǵallim stolları, kitapxana sóreleri — kóterme bahada, shártnama tiykarında.",
  build_title: "Qurılıs ushın hámmesi",
  build_sub: "Gerbish, shlakoblok, boslıqlı plitalar, beton, sheben — zavod bahasında.",
  how_title: "Qalay isleydi",
  how1_t: "Saylań", how1_d: "Katalogtan ónim hám muǵdardı saylań, qaldıq kórinip turadı.",
  how2_t: "Arza jiberiń", how2_d: "Fizikalıq yamasa yuridik tulǵa retinde maǵlıwmatlarıńızdı kiritiń.",
  how3_t: "Shártnama", how3_d: "Mekeme arzanı tastıyıqlaydı, shártnama PDF hám QR-kod penen tayar boladı.",
  how4_t: "Tólem hám jetkeriw", how4_d: "Click, Payme yamasa bank ótkeriwi. Jetkerip beriledi yamasa ózińiz alıp ketesiz.",
  b2b_title: "Shólkemler hám mámleketlik mekemeler ushın",
  b2b_sub: "Yuridik tulǵalar ushın shártnama bank ótkeriwi tiykarında dúziledi. Esap-faktura hám júk xatı beriledi.",
  b2b_cta: "Kóterme buyırtpa beriw",
  sellers_title: "Óndiriwshi mekemeler",
  products_n: "{n} ónim",
  price_on_request: "Bahası kelisiledi",
  per_unit: "/ {unit}",
  in_stock: "Bar: {n} {unit}",
  made_to_order: "Buyırtpa tiykarında",
  out_of_stock: "Qalmaǵan",
  add_to_cart: "Sebetke",
  in_cart: "Sebette",
  buy_now: "Arza beriw",
  qty: "Muǵdar",
  min_order: "Minimal buyırtpa: {n}",
  delivery_yes: "Jetkerip beriw bar",
  delivery_no: "Tek alıp ketiw",
  lead_days: "Tayarlaw: {n} kún",
  produced_at: "Islep shıǵarılǵan jer",
  specs: "Qásiyetleri",
  similar: "Uqsas ónimler",
  same_seller: "Usı mekemeniń basqa ónimleri",
  seller: "Óndiriwshi",
  sku: "Artikul",
  daily_capacity: "Kúnlik quwat",
  go_to_cart: "Sebetke ótiw",
  price_note: "Bahalar sumda. Juwmaqlawshı baha shártnamada belgilenedi.",
  filters: "Filtrler",
  reset: "Tazalaw",
  sort: "Saralaw",
  sort_popular: "Ataqlı",
  sort_price_asc: "Arzanıraq",
  sort_price_desc: "Qımbatıraq",
  sort_new: "Jańa",
  price_from: "den",
  price_to: "ge shekem",
  price: "Baha",
  only_in_stock: "Tek barları",
  with_delivery: "Jetkerip beriw menen",
  only_priced: "Bahası kórsetilgen",
  region: "Aymaq",
  found: "{n} ónim tabıldı",
  nothing_found: "Hesh nárse tabılmadı. Filtrlerdi ózgertip kóriń.",
  show_results: "Nátiyjelerdi kórsetiw",
  prev: "Aldınǵı",
  next: "Keyingi",
  cart_empty: "Sebet bos",
  cart_empty_sub: "Katalogtan kerekli ónimlerdi saylań.",
  go_shopping: "Satıp alıw",
  separate_note: "Hár bir mekeme menen jeke shártnama dúziledi — sebet mekemeler boyınsha toparlanǵan.",
  subtotal: "Aralıq summa",
  total: "Jámi",
  checkout: "Rásmiylestiriw",
  remove: "Óshiriw",
  items_n: "{n} ónim",
  priced_later: "Bahası kelisiletuǵın ónimlerdiń bahasın mekeme shártnamada belgileydi.",
  checkout_title: "Arzanı rásmiylestiriw",
  buyer_type: "Satıp alıwshı túri",
  individual: "Fizikalıq tulǵa",
  company: "Yuridik tulǵa / shólkem",
  full_name: "F.A.Á.",
  pinfl: "JSHSHIR (14 san)",
  passport: "Pasport seriyası hám nomeri",
  phone: "Telefon",
  email: "E-pochta",
  address: "Mánzil",
  company_name: "Shólkem atı",
  inn: "STIR",
  director: "Basshınıń F.A.Á.",
  bank_name: "Bank atı",
  bank_account: "Esap betı",
  mfo: "MFO",
  payment_method: "Tólem usılı",
  pay_click: "Click",
  pay_payme: "Payme",
  pay_bank: "Bank ótkeriwi",
  pay_online_note: "Shártnama tastıyıqlanǵannan keyin onlayn tólem siltemesi shıǵadı.",
  pay_bank_note: "Shártnamadaǵı rekvizitler boyınsha pul ótkeriledi.",
  delivery: "Jetkerip beriw",
  pickup: "Ózim alıp ketemen",
  delivery_to: "Mánzilge jetkeriw",
  delivery_address: "Jetkeriw mánzili",
  comment: "Túsinik",
  contract_lang: "Shártnama tili",
  submit: "Arza jiberiw",
  agree: "Arza jiberiw arqalı ashıq oferta hám shártnama shártlerine kelisim bildiresiz.",
  required: "Májbúriy maydan",
  success_title: "Arzańız qabıl etildi!",
  success_sub: "Mekeme arzanı kórip shıǵıp, shártnama dúzedi. Jaǵdaydı tómendegi silteme arqalı baqlań — arza nomeri hám telefon arqalı da tabıw múmkin.",
  app_number: "Arza nomeri",
  view_order: "Arzanı kóriw",
  your_data: "Maǵlıwmatlarıńız",
  order_summary: "Buyırtpa",
  order_title: "Arza {n}",
  st_new: "Jańa",
  st_review: "Kórip shıǵılmaqta",
  st_contract: "Shártnama dúzildi",
  st_rejected: "Biykar etildi",
  st_cancelled: "Toqtatıldı",
  c_active: "Tólem kútilmekte",
  c_paid: "Tólengen",
  c_shipped: "Jiberilgen",
  c_done: "Juwmaqlanǵan",
  c_cancelled: "Toqtatılǵan",
  contract: "Shártnama",
  download_pdf: "Shártnamanı júklep alıw (PDF)",
  open_pdf: "Shártnamanı ashıw",
  pay_now: "Tólew",
  pay_with: "{m} arqalı tólew",
  paid: "Tólengen",
  due: "Tóleniwi kerek",
  grand_total: "Ulıwma summa",
  bank_title: "Tólem rekvizitleri",
  bank_hint: "Tólem tapsırmasında shártnama nomerin kórsetiń.",
  waiting_seller: "Mekeme arzańızdı kórip shıqpaqta. Shártnama tayar bolǵanda usı bette payda boladı.",
  seller_comment: "Mekeme túsinigi",
  history: "Tariyx",
  cancel_order: "Arzanı toqtatıw",
  track_title: "Buyırtpanı baqlaw",
  track_sub: "Arza nomeri hám telefon nomerińizdi kiritiń.",
  order_number: "Arza nomeri",
  find: "Tabıw",
  not_found: "Tabılmadı. Maǵlıwmatlardı tekseriń.",
  via_agent: "{a} arqalı rásmiylestirilgen",
  delivery_cost: "Jetkerip beriw",
  verify_title: "Shártnamanı tekseriw",
  verify_ok: "Shártnama haqıyqıy",
  verify_bad: "Shártnama tabılmadı",
  contract_no: "Shártnama nomeri",
  date: "Sáne",
  buyer: "Satıp alıwshı",
  amount: "Summa",
  demo: "Demo",
  demo_title: "Demo tólem beti",
  demo_note: "Click/Payme gilt sózleri jalǵanǵansha tólem demo rejimde isleydi. Haqıyqıy pul alınbaydı.",
  demo_btn: "Tólemdi tastıyıqlaw (Demo)",
  demo_done: "Tólem qabıl etildi (Demo)",
  dashboard: "Basqarıw",
  my_products: "Ónimlerim",
  applications: "Arzalar",
  contracts: "Shártnamalar",
  general_catalog: "Ulıwma katalog",
  profile: "Profil",
  username: "Login",
  password: "Parol",
  sign_in: "Kiriw",
  wrong_login: "Login yamasa parol qáte",
  cabinet_login_sub: "Mekemeler ushın jeke login hám parol beriledi.",
  new_apps: "Jańa arzalar",
  active_contracts: "Aktiv shártnamalar",
  month_revenue: "Usı ay shártnamaları",
  receivable: "Debitorlıq",
  out_of_stock_n: "Qaldıǵı tawsılǵan",
  recent_apps: "Sońǵı arzalar",
  top_products: "Eń kóp satılǵanlar",
  add_product: "Ónim qosıw",
  edit: "Ózgertiw",
  save: "Saqlaw",
  cancel: "Biykarlaw",
  name: "Atı",
  spec: "Qásiyeti (ólshem, material)",
  description: "Táriypi",
  category: "Kategoriya",
  unit: "Ólshem birligi",
  stock: "Qaldıq",
  stock_hint: "Bos qaldırılsa — buyırtpa tiykarında",
  reserved: "Band",
  available: "Bar",
  active: "Aktiv",
  hidden: "Jasırın",
  image: "Súwret",
  upload_image: "Súwret júklew",
  tr_hint: "Tek ózbekshe (latın) jazsańız da boladı — kirill hám jańa álipbe avtomat toltırıladı.",
  confirm: "Tastıyıqlaw hám shártnama dúziw",
  reject: "Biykar etiw",
  reject_reason: "Biykar etiw sebebi",
  review: "Kórip shıǵıwǵa alıw",
  prepayment: "Aldınnan tólem, %",
  payment_days: "Tólem múddeti (bank kúni)",
  delivery_days: "Jetkeriw múddeti (kún)",
  register_payment: "Tólemdi belgilew",
  document_no: "Tólem tapsırması №",
  ship: "Jiberildi",
  complete: "Juwmaqlaw",
  cancel_contract: "Shártnamanı toqtatıw",
  regenerate: "PDF ti qayta jaratıw",
  pay_link: "Tólem siltemesi",
  copy: "Kóshirip alıw",
  copied: "Kóshirildi",
  agent_title: "Ulıwma katalog hám qaldıqlar",
  agent_sub: "Barlıq mekemeler ónimleri. Satıp alıwshıǵa basqa mekeme ónimin usınıp, shártnama shıǵarıwıńız múmkin — shártnama ónim iyesi atınan dúziledi.",
  owner: "Iyesi",
  add_to_deal: "Qosıw",
  deal: "Shártnama sebeti",
  create_deal: "Shártnama shıǵarıw",
  deal_note: "Hár bir ónim iyesi menen jeke shártnama dúziledi. Siz dánekershi retinde kórsetilesiz.",
  deal_done: "Shártnama(lar) dúzildi",
  scope_all: "Hámmesi",
  scope_own: "Maǵan kelgen",
  scope_agent: "Men rásmiylestirgen",
  actions: "Háreketler",
  status: "Jaǵday",
  created: "Jaratılǵan",
  profile_title: "Mekeme profili",
  requisites: "Shártnama rekvizitleri",
  legal_name: "Rásmiy atı (shártnamada)",
  treasury: "Ǵáziyneshilik jeke esap betı",
  change_password: "Paroldi ózgertiw",
  old_password: "Házirgi parol",
  new_password: "Jańa parol",
  saved: "Saqlandı",
  operator: "Operator",
  search_orders: "Nomer, satıp alıwshı, telefon…",
  no_data: "Maǵlıwmat joq",
  all: "Hámmesi",
  items: "Ónimler",
  pcs: "dana",
  price_per: "Baha (birlik)",
  view: "Kóriw",
  agent: "Dánekershi",
  notes: "Ishki túsinik",
  payments: "Tólemler",
  buyer_info: "Satıp alıwshı maǵlıwmatları",
  set_price: "Bahanı kiritiń",
  confirm_q: "Isenimińiz kámil me?",
  published: "Saytta kórinedi",
};
