# Generated by Django 5.2.17 on 2026-09-28 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("uzum", "Uzum Market"),
                            ("ozon", "Ozon"),
                            ("yandex", "Yandex Market"),
                            ("wb", "Wildberries"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=64,
                        verbose_name="Kategoriya ID (Ozon: description_category_id, WB: subjectID)",
                    ),
                ),
                (
                    "external_type_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Tip ID (faqat Ozon type_id)",
                    ),
                ),
                ("external_name", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mp_mappings",
                        to="market.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya moslash",
                "verbose_name_plural": "Kategoriya moslash",
                "unique_together": {("category", "marketplace")},
            },
        ),
        migrations.CreateModel(
            name="AttributeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("required", models.BooleanField(default=False)),
                (
                    "is_dictionary",
                    models.BooleanField(
                        default=False, verbose_name="Qiymat lug'atdan tanlanadi"
                    ),
                ),
                ("multi", models.BooleanField(default=False)),
                (
                    "value_type",
                    models.CharField(
                        blank=True,
                        help_text="marketplace qaytargan tur (string/number/...)",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("const", "Doimiy qiymat"),
                            ("field", "Mahsulot maydoni"),
                            ("product", "Har bir mahsulotda kiritiladi"),
                        ],
                        default="const",
                        max_length=8,
                    ),
                ),
                ("field", models.CharField(blank=True, max_length=32)),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Doimiy qiymat"
                    ),
                ),
                (
                    "value_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Doimiy qiymat ID (lug'at)",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=64)),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Lug'at qiymatlari (marketplace bergan bo'lsa)",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="integrations.categorymapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-required", "name"],
                "unique_together": {("mapping", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ccy", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=4, max_digits=14)),
                ("nominal", models.PositiveIntegerField(default=1)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("ccy", "date")},
            },
        ),
        migrations.CreateModel(
            name="ExternalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("uzum", "Uzum Market"),
                            ("ozon", "Ozon"),
                            ("yandex", "Yandex Market"),
                            ("wb", "Wildberries"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("type_id", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(blank=True, max_length=1000)),
                ("search", models.CharField(blank=True, max_length=1000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["path"],
                "unique_together": {("marketplace", "external_id", "type_id")},
            },
        ),
        migrations.CreateModel(
            name="MarketplaceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("uzum", "Uzum Market"),
                            ("ozon", "Ozon"),
                            ("yandex", "Yandex Market"),
                            ("wb", "Wildberries"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Nomi (ichki)"
                    ),
                ),
                (
                    "cabinet_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Kabinet / do'kon ID"
                    ),
                ),
                (
                    "campaign_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Kampaniya (magazin) ID — Yandex",
                    ),
                ),
                (
                    "warehouse_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Ombor ID (FBS)"
                    ),
                ),
                ("credentials_enc", models.TextField(blank=True, editable=False)),
                (
                    "secret_last4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Tekshirilmoqda"),
                            ("active", "Faol"),
                            ("invalid", "Kalit yaroqsiz"),
                            ("disabled", "O'chirilgan"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("status_message", models.CharField(blank=True, max_length=500)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("key_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Kabinetdan olingan ma'lumot (do'konlar, omborlar, ruxsatlar)",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Marketplace'ga xos sozlamalar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "so'm"), ("RUB", "rubl")],
                        default="UZS",
                        max_length=3,
                        verbose_name="Kabinet valyutasi",
                    ),
                ),
                (
                    "rate_source",
                    models.CharField(
                        choices=[
                            ("cbu", "Markaziy bank kursi (cbu.uz)"),
                            ("manual", "Qo'lda kiritilgan kurs"),
                        ],
                        default="cbu",
                        max_length=8,
                        verbose_name="Kurs manbai",
                    ),
                ),
                (
                    "manual_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Qo'lda kurs (1 birlik = N so'm)",
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Ustama, %",
                    ),
                ),
                (
                    "stock_buffer",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Zaxira (marketplace'ga ko'rsatilmaydi)"
                    ),
                ),
                (
                    "mto_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 — bunday mahsulotlar marketplace'da 0 qoldiq bilan turadi",
                        verbose_name="«Buyurtma asosida» mahsulot uchun ko'rsatiladigan qoldiq",
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True, verbose_name="Narx/qoldiqni avtomatik yangilash"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Yoqilgan"),
                ),
                ("orders_synced_at", models.DateTimeField(blank=True, null=True)),
                ("stock_synced_at", models.DateTimeField(blank=True, null=True)),
                ("status_polled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mp_accounts",
                        to="market.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace kabineti",
                "verbose_name_plural": "Marketplace kabinetlari",
                "ordering": ["seller_id", "marketplace", "id"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=48)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=10),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=6)),
                (
                    "run_after",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("last_error", models.TextField(blank=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="integrations.marketplaceaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductMarketInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=128)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Shtrix-kod"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="O'zbekiston",
                        max_length=64,
                        verbose_name="Ishlab chiqarilgan mamlakat",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_info",
                        to="market.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=48)),
                ("method", models.CharField(blank=True, max_length=8)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.marketplaceaccount",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="integrations.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValueMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("our_value", models.CharField(max_length=255)),
                ("external_value_id", models.CharField(blank=True, max_length=64)),
                ("external_value", models.CharField(blank=True, max_length=255)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_map",
                        to="integrations.attributemapping",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute", "our_value")},
            },
        ),
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_id",
                    models.CharField(
                        max_length=64,
                        verbose_name="Sotuvchi artikuli (offer_id / vendorCode)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Marketplace ID (product_id / nmID / productId)",
                    ),
                ),
                (
                    "external_sku",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="SKU (Ozon sku / WB chrtID / Uzum skuId)",
                    ),
                ),
                ("external_meta", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("pending", "Tekshiruvda"),
                            ("active", "Faol"),
                            ("rejected", "Rad etilgan"),
                            ("error", "Xato"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=128)),
                (
                    "pushed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("pushed_currency", models.CharField(blank=True, max_length=3)),
                ("pushed_stock", models.IntegerField(blank=True, null=True)),
                ("price_synced_at", models.DateTimeField(blank=True, null=True)),
                ("stock_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="integrations.marketplaceaccount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mp_listings",
                        to="market.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("account", "offer_id"), ("product", "account")},
            },
        ),
        migrations.CreateModel(
            name="MarketplaceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                (
                    "scheme",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Model (FBS/FBO/DBS)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Marketplace statusi"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("processing", "Yig'ilmoqda"),
                            ("shipped", "Jo'natildi"),
                            ("delivered", "Yetkazildi"),
                            ("cancelled", "Bekor qilindi"),
                            ("returned", "Qaytarildi"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("items", models.JSONField(default=list)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("stock_state", models.CharField(default="none", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="integrations.marketplaceaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at", "-id"],
                "unique_together": {("account", "external_id")},
            },
        ),
    ]
