# Generated by Django 5.2.17 on 2026-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceorder",
            name="stock_items",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
