"""Shartnoma matni 6 tilda. uz_cyrl va uz_new lotindagi matndan avtomatik o'giriladi.

Qonunchilik tayanchlari (O'zR): Fuqarolik kodeksi (oldi-sotdi, 386-bob), "Xo'jalik yurituvchi
subyektlar faoliyatining shartnomaviy-huquqiy bazasi to'g'risida"gi Qonun (penyalar),
"Iste'molchilarning huquqlarini himoya qilish to'g'risida"gi Qonun (B2C).
Matnni yuridik bo'lim ko'rib chiqishi kerak — bu ishchi shablon.
"""
import re

from .translit import to_cyrl, to_new

UZ = {
    "title": "OLDI-SOTDI SHARTNOMASI № {number}",
    "city_date": "{city}, {date}",
    "pre_b2b": "{seller}, (keyingi o'rinlarda «Sotuvchi») nomidan rahbar {seller_director} bir tomondan, va {buyer}, (keyingi o'rinlarda «Xaridor») nomidan {buyer_director} ikkinchi tomondan, ushbu shartnomani quyidagilar haqida tuzdilar:",
    "pre_b2c": "{seller}, (keyingi o'rinlarda «Sotuvchi») nomidan rahbar {seller_director} bir tomondan, va fuqaro {buyer} (JShShIR: {pinfl}, pasport: {passport}), (keyingi o'rinlarda «Xaridor») ikkinchi tomondan, ushbu shartnomani quyidagilar haqida tuzdilar:",
    "agent_note": "Shartnoma {agent} tomonidan {platform} platformasi orqali Sotuvchi nomidan rasmiylashtirildi. Barcha majburiyatlar Sotuvchi zimmasida.",
    "s1": "1. SHARTNOMA PREDMETI",
    "s1_1": "1.1. Sotuvchi ushbu shartnomaning ajralmas qismi bo'lgan Spetsifikatsiyada ko'rsatilgan mahsulotlarni Xaridorga topshirish, Xaridor esa ularni qabul qilib olish va haqini to'lash majburiyatini oladi.",
    "s1_2": "1.2. Mahsulot Sotuvchining o'z ishlab chiqarishida tayyorlangan.",
    "s2": "2. SHARTNOMA SUMMASI",
    "s2_1": "2.1. Shartnomaning umumiy summasi {total} so'mni tashkil etadi, shu jumladan yetkazib berish xarajati {delivery} so'm.",
    "s2_2": "2.2. Narxlar O'zbekiston Respublikasi so'mida belgilangan. QQS qonunchilikka muvofiq qo'llaniladi.",
    "s3": "3. TO'LOV TARTIBI",
    "s3_bank": "3.1. Xaridor shartnoma summasining {prepay}% miqdorini shartnoma imzolangan kundan boshlab {pay_days} bank kuni ichida Sotuvchining hisob raqamiga pul o'tkazish yo'li bilan to'laydi. Qolgan qism mahsulot qabul qilingandan keyin 5 bank kuni ichida to'lanadi.",
    "s3_online": "3.1. Xaridor shartnoma summasini {platform} platformasi orqali {method} to'lov tizimi yordamida 100% oldindan to'laydi. To'lov Sotuvchi hisobiga o'tgan paytdan boshlab to'langan hisoblanadi.",
    "s3_2": "3.2. To'lov amalga oshirilgan sana — pul mablag'lari Sotuvchi hisob raqamiga kelib tushgan sana.",
    "s4": "4. YETKAZIB BERISH VA QABUL QILISH",
    "s4_delivery": "4.1. Sotuvchi mahsulotni to'lov tushgan kundan boshlab {del_days} kun ichida Xaridor ko'rsatgan manzilga yetkazib beradi: {address}.",
    "s4_pickup": "4.1. Xaridor mahsulotni to'lov tushgan kundan boshlab {del_days} kun ichida Sotuvchining ishlab chiqarish manzilidan o'zi olib ketadi.",
    "s4_2": "4.2. Mahsulot yuk xati (B2B holatda — elektron hisob-faktura) asosida topshiriladi. Mulk huquqi va tasodifiy nobud bo'lish xavfi mahsulot Xaridorga topshirilgan paytdan o'tadi.",
    "s5": "5. SIFAT VA KAFOLAT",
    "s5_1": "5.1. Mahsulot sifati amaldagi standartlar va Spetsifikatsiyadagi xususiyatlarga mos bo'lishi kerak.",
    "s5_2": "5.2. Sifat yoki miqdor bo'yicha e'tirozlar mahsulot qabul qilingan kundan boshlab 10 kun ichida yozma ravishda bildiriladi. Asosli e'tirozda Sotuvchi mahsulotni o'z hisobidan almashtiradi yoki kamchilikni bartaraf etadi.",
    "s6": "6. TOMONLARNING JAVOBGARLIGI",
    "s6_b2b": "6.1. To'lov kechiktirilganda Xaridor kechiktirilgan har bir kun uchun to'lanmagan summaning 0,4 foizi miqdorida, biroq 50 foizidan oshmagan penya to'laydi. Mahsulot yetkazib berish kechiktirilganda Sotuvchi bajarilmagan majburiyat qiymatining har bir kun uchun 0,5 foizi miqdorida, biroq 50 foizidan oshmagan penya to'laydi.",
    "s6_b2c": "6.1. Tomonlar shartnoma majburiyatlarini bajarmaganlik uchun O'zbekiston Respublikasining «Iste'molchilarning huquqlarini himoya qilish to'g'risida»gi Qonuni va boshqa qonun hujjatlariga muvofiq javobgar bo'ladi.",
    "s7": "7. FORS-MAJOR",
    "s7_1": "7.1. Tomonlar yengib bo'lmaydigan kuch (fors-major) holatlari natijasida majburiyatlarni bajarmaganlik uchun javobgar bo'lmaydi. Bunday holat haqida 5 kun ichida xabar beriladi.",
    "s8": "8. NIZOLARNI HAL QILISH",
    "s8_1": "8.1. Nizolar muzokaralar yo'li bilan, kelishilmagan taqdirda — {court} hal qilinadi.",
    "court_b2b": "Sotuvchi joylashgan yerdagi iqtisodiy sudda",
    "court_b2c": "qonunchilikda belgilangan sudlovga taalluqlilik bo'yicha sudda",
    "s9": "9. YAKUNIY QOIDALAR",
    "s9_1": "9.1. Shartnoma {platform} platformasida elektron shaklda tuzilgan bo'lib, Xaridor arizasi va to'lov amalga oshirilishi shartnoma shartlarining aksepti hisoblanadi. Tomonlar xohishiga ko'ra shartnoma E-IMZO orqali ham imzolanishi mumkin.",
    "s9_2": "9.2. Shartnoma imzolangan kundan boshlab kuchga kiradi va majburiyatlar to'liq bajarilgunga qadar amal qiladi.",
    "s9_3": "9.3. Shartnoma haqiqiyligini QR-kod orqali tekshirish mumkin.",
    "spec": "SPETSIFIKATSIYA (1-ilova)",
    "col_no": "№", "col_name": "Mahsulot nomi", "col_unit": "O'lch.", "col_qty": "Miqdor", "col_price": "Narx, so'm", "col_sum": "Summa, so'm",
    "items_total": "Mahsulotlar jami", "delivery": "Yetkazib berish", "grand": "JAMI",
    "req": "10. TOMONLARNING REKVIZITLARI",
    "seller": "SOTUVCHI", "buyer": "XARIDOR",
    "inn": "STIR", "pinfl": "JShShIR", "passport": "Pasport", "address": "Manzil", "phone": "Tel.",
    "bank": "Bank", "account": "H/r", "mfo": "MFO", "director": "Rahbar", "sign": "Imzo",
    "verify": "Tekshirish",
    "not_set": "—",
    "pay_bank": "bank o'tkazmasi", "pay_click": "Click", "pay_payme": "Payme",
}

RU = {
    "title": "ДОГОВОР КУПЛИ-ПРОДАЖИ № {number}",
    "city_date": "{city}, {date}",
    "pre_b2b": "{seller}, именуемое в дальнейшем «Продавец», в лице руководителя {seller_director}, с одной стороны, и {buyer}, именуемое в дальнейшем «Покупатель», в лице {buyer_director}, с другой стороны, заключили настоящий договор о нижеследующем:",
    "pre_b2c": "{seller}, именуемое в дальнейшем «Продавец», в лице руководителя {seller_director}, с одной стороны, и гражданин(ка) {buyer} (ПИНФЛ: {pinfl}, паспорт: {passport}), именуемый(ая) в дальнейшем «Покупатель», с другой стороны, заключили настоящий договор о нижеследующем:",
    "agent_note": "Договор оформлен {agent} через платформу {platform} от имени Продавца. Все обязательства несёт Продавец.",
    "s1": "1. ПРЕДМЕТ ДОГОВОРА",
    "s1_1": "1.1. Продавец обязуется передать Покупателю продукцию, указанную в Спецификации, являющейся неотъемлемой частью договора, а Покупатель — принять и оплатить её.",
    "s1_2": "1.2. Продукция изготовлена на собственном производстве Продавца.",
    "s2": "2. СУММА ДОГОВОРА",
    "s2_1": "2.1. Общая сумма договора составляет {total} сум, в том числе стоимость доставки {delivery} сум.",
    "s2_2": "2.2. Цены установлены в национальной валюте Республики Узбекистан. НДС применяется в соответствии с законодательством.",
    "s3": "3. ПОРЯДОК ОПЛАТЫ",
    "s3_bank": "3.1. Покупатель перечисляет {prepay}% суммы договора на расчётный счёт Продавца в течение {pay_days} банковских дней с даты подписания договора. Оставшаяся часть оплачивается в течение 5 банковских дней после приёмки продукции.",
    "s3_online": "3.1. Покупатель производит 100% предоплату через платформу {platform} с помощью платёжной системы {method}. Оплата считается произведённой с момента зачисления средств на счёт Продавца.",
    "s3_2": "3.2. Датой оплаты считается дата поступления денежных средств на счёт Продавца.",
    "s4": "4. ПОСТАВКА И ПРИЁМКА",
    "s4_delivery": "4.1. Продавец доставляет продукцию в течение {del_days} дней с даты оплаты по адресу Покупателя: {address}.",
    "s4_pickup": "4.1. Покупатель самостоятельно вывозит продукцию с производственного адреса Продавца в течение {del_days} дней с даты оплаты.",
    "s4_2": "4.2. Продукция передаётся по товарной накладной (для юридических лиц — электронной счёт-фактуре). Право собственности и риск случайной гибели переходят к Покупателю с момента передачи продукции.",
    "s5": "5. КАЧЕСТВО И ГАРАНТИЯ",
    "s5_1": "5.1. Качество продукции должно соответствовать действующим стандартам и характеристикам, указанным в Спецификации.",
    "s5_2": "5.2. Претензии по качеству или количеству предъявляются в письменной форме в течение 10 дней с даты приёмки. При обоснованной претензии Продавец за свой счёт заменяет продукцию или устраняет недостатки.",
    "s6": "6. ОТВЕТСТВЕННОСТЬ СТОРОН",
    "s6_b2b": "6.1. За просрочку оплаты Покупатель уплачивает пеню в размере 0,4% от неоплаченной суммы за каждый день просрочки, но не более 50%. За просрочку поставки Продавец уплачивает пеню в размере 0,5% от стоимости неисполненного обязательства за каждый день, но не более 50%.",
    "s6_b2c": "6.1. Стороны несут ответственность в соответствии с Законом Республики Узбекистан «О защите прав потребителей» и иными актами законодательства.",
    "s7": "7. ФОРС-МАЖОР",
    "s7_1": "7.1. Стороны освобождаются от ответственности за неисполнение обязательств вследствие обстоятельств непреодолимой силы. Сторона уведомляет о таких обстоятельствах в течение 5 дней.",
    "s8": "8. РАЗРЕШЕНИЕ СПОРОВ",
    "s8_1": "8.1. Споры разрешаются путём переговоров, а при недостижении согласия — {court}.",
    "court_b2b": "в экономическом суде по месту нахождения Продавца",
    "court_b2c": "в суде в соответствии с подсудностью, установленной законодательством",
    "s9": "9. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ",
    "s9_1": "9.1. Договор заключён в электронной форме на платформе {platform}; подача заявки и оплата Покупателем являются акцептом условий договора. По желанию сторон договор может быть подписан посредством E-IMZO.",
    "s9_2": "9.2. Договор вступает в силу с даты подписания и действует до полного исполнения обязательств.",
    "s9_3": "9.3. Подлинность договора проверяется по QR-коду.",
    "spec": "СПЕЦИФИКАЦИЯ (Приложение 1)",
    "col_no": "№", "col_name": "Наименование", "col_unit": "Ед.", "col_qty": "Кол-во", "col_price": "Цена, сум", "col_sum": "Сумма, сум",
    "items_total": "Итого по продукции", "delivery": "Доставка", "grand": "ВСЕГО",
    "req": "10. РЕКВИЗИТЫ СТОРОН",
    "seller": "ПРОДАВЕЦ", "buyer": "ПОКУПАТЕЛЬ",
    "inn": "ИНН", "pinfl": "ПИНФЛ", "passport": "Паспорт", "address": "Адрес", "phone": "Тел.",
    "bank": "Банк", "account": "Р/с", "mfo": "МФО", "director": "Руководитель", "sign": "Подпись",
    "verify": "Проверка",
    "not_set": "—",
    "pay_bank": "банковский перевод", "pay_click": "Click", "pay_payme": "Payme",
}

EN = {
    "title": "SALE AND PURCHASE AGREEMENT No. {number}",
    "city_date": "{city}, {date}",
    "pre_b2b": "{seller} (the “Seller”), represented by its head {seller_director}, on the one part, and {buyer} (the “Buyer”), represented by {buyer_director}, on the other part, have concluded this Agreement as follows:",
    "pre_b2c": "{seller} (the “Seller”), represented by its head {seller_director}, on the one part, and {buyer}, an individual (PINFL: {pinfl}, passport: {passport}) (the “Buyer”), on the other part, have concluded this Agreement as follows:",
    "agent_note": "This Agreement was executed by {agent} via the {platform} platform on behalf of the Seller. All obligations rest with the Seller.",
    "s1": "1. SUBJECT OF THE AGREEMENT",
    "s1_1": "1.1. The Seller shall deliver to the Buyer the goods listed in the Specification, which forms an integral part of this Agreement, and the Buyer shall accept and pay for them.",
    "s1_2": "1.2. The goods are manufactured at the Seller's own production facilities.",
    "s2": "2. CONTRACT PRICE",
    "s2_1": "2.1. The total contract price is UZS {total}, including delivery costs of UZS {delivery}.",
    "s2_2": "2.2. Prices are set in Uzbek soum (UZS). VAT is applied in accordance with the law.",
    "s3": "3. PAYMENT TERMS",
    "s3_bank": "3.1. The Buyer shall transfer {prepay}% of the contract price to the Seller's bank account within {pay_days} banking days of signing. The balance is payable within 5 banking days after acceptance of the goods.",
    "s3_online": "3.1. The Buyer shall pay 100% in advance through the {platform} platform using the {method} payment system. Payment is deemed made once funds are credited to the Seller.",
    "s3_2": "3.2. The payment date is the date the funds are received in the Seller's account.",
    "s4": "4. DELIVERY AND ACCEPTANCE",
    "s4_delivery": "4.1. The Seller shall deliver the goods within {del_days} days of payment to the Buyer's address: {address}.",
    "s4_pickup": "4.1. The Buyer shall collect the goods from the Seller's production address within {del_days} days of payment.",
    "s4_2": "4.2. Goods are handed over against a waybill (for legal entities — an electronic invoice). Title and risk of accidental loss pass to the Buyer upon handover.",
    "s5": "5. QUALITY AND WARRANTY",
    "s5_1": "5.1. The goods shall comply with applicable standards and the characteristics stated in the Specification.",
    "s5_2": "5.2. Claims regarding quality or quantity shall be made in writing within 10 days of acceptance. For a justified claim the Seller shall replace the goods or remedy the defects at its own cost.",
    "s6": "6. LIABILITY",
    "s6_b2b": "6.1. For late payment the Buyer shall pay a penalty of 0.4% of the unpaid amount per day of delay, not exceeding 50%. For late delivery the Seller shall pay a penalty of 0.5% of the value of the unfulfilled obligation per day, not exceeding 50%.",
    "s6_b2c": "6.1. The parties are liable in accordance with the Law of the Republic of Uzbekistan “On Consumer Rights Protection” and other legislation.",
    "s7": "7. FORCE MAJEURE",
    "s7_1": "7.1. The parties are released from liability for non-performance caused by force majeure. The affected party shall notify the other within 5 days.",
    "s8": "8. DISPUTE RESOLUTION",
    "s8_1": "8.1. Disputes shall be settled by negotiation, failing which — {court}.",
    "court_b2b": "by the economic court at the Seller's location",
    "court_b2c": "by the competent court in accordance with the law",
    "s9": "9. FINAL PROVISIONS",
    "s9_1": "9.1. This Agreement is concluded electronically on the {platform} platform; the Buyer's application and payment constitute acceptance of its terms. At the parties' discretion it may also be signed with E-IMZO.",
    "s9_2": "9.2. The Agreement enters into force on signing and remains valid until all obligations are fulfilled.",
    "s9_3": "9.3. Authenticity can be verified via the QR code.",
    "spec": "SPECIFICATION (Annex 1)",
    "col_no": "No.", "col_name": "Item", "col_unit": "Unit", "col_qty": "Qty", "col_price": "Price, UZS", "col_sum": "Amount, UZS",
    "items_total": "Goods subtotal", "delivery": "Delivery", "grand": "TOTAL",
    "req": "10. DETAILS OF THE PARTIES",
    "seller": "SELLER", "buyer": "BUYER",
    "inn": "TIN", "pinfl": "PINFL", "passport": "Passport", "address": "Address", "phone": "Tel.",
    "bank": "Bank", "account": "Account", "mfo": "MFO", "director": "Head", "sign": "Signature",
    "verify": "Verify",
    "not_set": "—",
    "pay_bank": "bank transfer", "pay_click": "Click", "pay_payme": "Payme",
}

KAA = {
    "title": "SATIW-SATIP ALIW SHÁRTNAMASI № {number}",
    "city_date": "{city}, {date}",
    "pre_b2b": "{seller}, (keyingi orınlarda «Satıwshı») atınan basshı {seller_director} bir tárepten, hám {buyer}, (keyingi orınlarda «Satıp alıwshı») atınan {buyer_director} ekinshi tárepten, usı shártnamanı tómendegiler haqqında dúzdi:",
    "pre_b2c": "{seller}, (keyingi orınlarda «Satıwshı») atınan basshı {seller_director} bir tárepten, hám puqara {buyer} (JSHSHIR: {pinfl}, pasport: {passport}), (keyingi orınlarda «Satıp alıwshı») ekinshi tárepten, usı shártnamanı tómendegiler haqqında dúzdi:",
    "agent_note": "Shártnama {agent} tárepinen {platform} platforması arqalı Satıwshı atınan rásmiylestirildi. Barlıq minnetlemeler Satıwshı moynında.",
    "s1": "1. SHÁRTNAMA PREDMETI",
    "s1_1": "1.1. Satıwshı shártnamanıń ajıralmas bólegi bolǵan Specifikaciyada kórsetilgen ónimlerdi Satıp alıwshıǵa tapsırıw, Satıp alıwshı bolsa olardı qabıl etiw hám haqısın tólew minnetlemesin aladı.",
    "s1_2": "1.2. Ónim Satıwshınıń óz óndirisinde tayarlanǵan.",
    "s2": "2. SHÁRTNAMA SUMMASI",
    "s2_1": "2.1. Shártnamanıń ulıwma summası {total} sum, sonıń ishinde jetkerip beriw qárejeti {delivery} sum.",
    "s2_2": "2.2. Bahalar Ózbekstan Respublikası sumında belgilengen. QQS nızamshılıqqa muwapıq qollanıladı.",
    "s3": "3. TÓLEM TÁRTIBI",
    "s3_bank": "3.1. Satıp alıwshı shártnama summasınıń {prepay}% muǵdarın shártnama qol qoyılǵan kúnnen baslap {pay_days} bank kúni ishinde Satıwshınıń esap betine ótkeriw arqalı tóleydi. Qalǵan bólegi ónim qabıl etilgennen keyin 5 bank kúni ishinde tólenedi.",
    "s3_online": "3.1. Satıp alıwshı shártnama summasın {platform} platforması arqalı {method} tólem sisteması járdeminde 100% aldınnan tóleydi.",
    "s3_2": "3.2. Tólem sánesi — qarjılar Satıwshınıń esap betine túsken sáne.",
    "s4": "4. JETKERIP BERIW HÁM QABIL ETIW",
    "s4_delivery": "4.1. Satıwshı ónimdi tólem túsken kúnnen baslap {del_days} kún ishinde Satıp alıwshınıń mánziline jetkerip beredi: {address}.",
    "s4_pickup": "4.1. Satıp alıwshı ónimdi tólem túsken kúnnen baslap {del_days} kún ishinde Satıwshınıń óndiris mánzilinen ózi alıp ketedi.",
    "s4_2": "4.2. Ónim júk xatı (yuridik tulǵalar ushın — elektron esap-faktura) tiykarında tapsırıladı. Múlk huqıqı ónim tapsırılǵan waqıttan ótedi.",
    "s5": "5. SAPA HÁM KEPILLIK",
    "s5_1": "5.1. Ónim sapası ámeldegi standartlarǵa hám Specifikaciyadaǵı qásiyetlerge sáykes bolıwı kerek.",
    "s5_2": "5.2. Sapa yamasa muǵdar boyınsha pretenziyalar ónim qabıl etilgen kúnnen baslap 10 kún ishinde jazba túrde bildiriledi.",
    "s6": "6. TÁREPLERDIŃ JUWAPKERSHILIGI",
    "s6_b2b": "6.1. Tólem keshiktirilse Satıp alıwshı hár bir kún ushın tólenbegen summanıń 0,4 procenti, biraq 50 procentinen aspaytuǵın penya tóleydi. Jetkerip beriw keshiktirilse Satıwshı hár bir kún ushın 0,5 procent, biraq 50 procentinen aspaytuǵın penya tóleydi.",
    "s6_b2c": "6.1. Tárepler Ózbekstan Respublikasınıń «Tutınıwshılardıń huqıqların qorǵaw haqqında»ǵı Nızamına muwapıq juwapker boladı.",
    "s7": "7. FORS-MAJOR",
    "s7_1": "7.1. Tárepler fors-major jaǵdayları nátiyjesinde minnetlemelerdi orınlamaǵanlıǵı ushın juwapker bolmaydı.",
    "s8": "8. DAWLARDI SHESHIW",
    "s8_1": "8.1. Dawlar kelisiwler arqalı, kelisilmegen jaǵdayda — {court} sheshiledi.",
    "court_b2b": "Satıwshı jaylasqan jerdegi ekonomikalıq sudta",
    "court_b2c": "nızamshılıqta belgilengen sudta",
    "s9": "9. JUWMAQLAWSHI QAǴIYDALAR",
    "s9_1": "9.1. Shártnama {platform} platformasında elektron túrde dúzilgen; Satıp alıwshınıń arzası hám tólemi shártnama shártleriniń aktsepti bolıp esaplanadı. Tárepler qálese E-IMZO arqalı da qol qoyıladı.",
    "s9_2": "9.2. Shártnama qol qoyılǵan kúnnen baslap kúshke kiredi hám minnetlemeler tolıq orınlanǵanǵa shekem ámel etedi.",
    "s9_3": "9.3. Shártnamanıń haqıyqıylıǵın QR-kod arqalı tekseriw múmkin.",
    "spec": "SPECIFIKACIYA (1-qosımsha)",
    "col_no": "№", "col_name": "Ónim atı", "col_unit": "Ól.", "col_qty": "Muǵdar", "col_price": "Baha, sum", "col_sum": "Summa, sum",
    "items_total": "Ónimler jámi", "delivery": "Jetkerip beriw", "grand": "JÁMI",
    "req": "10. TÁREPLERDIŃ REKVIZITLERI",
    "seller": "SATIWSHI", "buyer": "SATIP ALIWSHI",
    "inn": "STIR", "pinfl": "JSHSHIR", "passport": "Pasport", "address": "Mánzil", "phone": "Tel.",
    "bank": "Bank", "account": "E/b", "mfo": "MFO", "director": "Basshı", "sign": "Qol",
    "verify": "Tekseriw",
    "not_set": "—",
    "pay_bank": "bank ótkeriwi", "pay_click": "Click", "pay_payme": "Payme",
}


KEEP = {"Click", "Payme", "E-IMZO", "QR", "B2B", "B2C"}


def _conv(d, fn):
    out = {}
    for k, v in d.items():
        # {placeholder} larni o'girmaslik
        parts = re.split(r"(\{[a-z_]+\}|Click|Payme|E-IMZO|QR|B2B|B2C)", v)
        out[k] = "".join(p if (p.startswith("{") or p in KEEP) else fn(p) for p in parts)
    return out


TEXTS = {
    "uz": UZ,
    "uz_cyrl": _conv(UZ, to_cyrl),
    "uz_new": _conv(UZ, to_new),
    "ru": RU,
    "en": EN,
    "kaa": KAA,
}


def texts(lang):
    return TEXTS.get(lang) or UZ
