# Generated by Django 5.2.17 on 2026-09-28 07:30

import django.db.models.deletion
import django.utils.timezone
import market.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(default="box", max_length=32)),
                ("name", models.JSONField(default=market.models.i18n_default)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("seller", "Sotuvchi muassasa"),
                            ("operator", "Operator (JIED)"),
                        ],
                        default="seller",
                        max_length=16,
                    ),
                ),
                ("name", models.JSONField(default=market.models.i18n_default)),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Rasmiy nomi (shartnoma uchun)",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=16, verbose_name="STIR"),
                ),
                ("region", models.CharField(blank=True, max_length=64)),
                ("region_i18n", models.JSONField(default=market.models.i18n_default)),
                ("district_i18n", models.JSONField(default=market.models.i18n_default)),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yuridik manzil"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("email", models.CharField(blank=True, max_length=128)),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Rahbar F.I.Sh."
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=128, verbose_name="Bank"),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Hisob raqami"
                    ),
                ),
                (
                    "bank_mfo",
                    models.CharField(blank=True, max_length=16, verbose_name="MFO"),
                ),
                (
                    "treasury_account",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="G'aznachilik sh/h"
                    ),
                ),
                (
                    "description",
                    models.JSONField(blank=True, default=market.models.i18n_default),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="sellers/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("contract_seq", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sotuvchi muassasa",
                "verbose_name_plural": "Sotuvchi muassasalar",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("b2b", "Yuridik shaxs (B2B)"),
                            ("b2c", "Jismoniy shaxs (B2C)"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        max_length=255, verbose_name="Tashkilot nomi yoki F.I.Sh."
                    ),
                ),
                (
                    "buyer_inn",
                    models.CharField(blank=True, max_length=16, verbose_name="STIR"),
                ),
                (
                    "buyer_pinfl",
                    models.CharField(blank=True, max_length=16, verbose_name="JShShIR"),
                ),
                (
                    "buyer_passport",
                    models.CharField(blank=True, max_length=16, verbose_name="Pasport"),
                ),
                (
                    "buyer_director",
                    models.CharField(blank=True, max_length=128, verbose_name="Rahbar"),
                ),
                ("buyer_phone", models.CharField(max_length=32)),
                ("buyer_email", models.CharField(blank=True, max_length=128)),
                ("buyer_address", models.CharField(blank=True, max_length=255)),
                ("buyer_region", models.CharField(blank=True, max_length=64)),
                ("buyer_bank_name", models.CharField(blank=True, max_length=128)),
                ("buyer_bank_account", models.CharField(blank=True, max_length=32)),
                ("buyer_bank_mfo", models.CharField(blank=True, max_length=16)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("payme", "Payme"),
                            ("bank", "Bank o'tkazmasi (perechisleniye)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("delivery_required", models.BooleanField(default=False)),
                ("delivery_address", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("seller_comment", models.TextField(blank=True)),
                ("lang", models.CharField(default="uz", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("review", "Ko'rib chiqilmoqda"),
                            ("contract", "Shartnoma tuzildi"),
                            ("rejected", "Rad etildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("has_unpriced", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boshqa muassasa nomidan ariza/shartnoma yaratgan muassasa",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_applications",
                        to="market.seller",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="market.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ariza",
                "verbose_name_plural": "Arizalar",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40, unique=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("b2b", "Yuridik shaxs (B2B)"),
                            ("b2c", "Jismoniy shaxs (B2C)"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("payme", "Payme"),
                            ("bank", "Bank o'tkazmasi (perechisleniye)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("lang", models.CharField(default="uz", max_length=8)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("prepayment_percent", models.PositiveIntegerField(default=100)),
                ("payment_days", models.PositiveIntegerField(default=10)),
                ("delivery_days", models.PositiveIntegerField(default=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Imzolandi — to'lov kutilmoqda"),
                            ("paid", "To'landi"),
                            ("shipped", "Jo'natildi"),
                            ("done", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract",
                        to="market.application",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_contracts",
                        to="market.seller",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="market.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma",
                "verbose_name_plural": "Shartnomalar",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("payme", "Payme"),
                            ("bank", "Bank o'tkazmasi (perechisleniye)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "provider_txn_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("provider_state", models.IntegerField(default=0)),
                ("provider_create_time", models.BigIntegerField(default=0)),
                ("provider_perform_time", models.BigIntegerField(default=0)),
                ("provider_cancel_time", models.BigIntegerField(default=0)),
                ("provider_reason", models.IntegerField(blank=True, null=True)),
                (
                    "document_no",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="To'lov topshiriqnomasi №",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="market.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=32, unique=True)),
                ("name", models.JSONField(default=market.models.i18n_default)),
                (
                    "spec",
                    models.JSONField(
                        blank=True,
                        default=market.models.i18n_default,
                        verbose_name="Xususiyati",
                    ),
                ),
                (
                    "description",
                    models.JSONField(blank=True, default=market.models.i18n_default),
                ),
                ("unit", models.CharField(default="dona", max_length=16)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Narx (so'm, QQSsiz)",
                    ),
                ),
                ("min_order", models.PositiveIntegerField(default=1)),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Bo'sh = buyurtma asosida",
                        null=True,
                        verbose_name="Omborda bor",
                    ),
                ),
                (
                    "reserved",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Band qilingan"
                    ),
                ),
                (
                    "daily_capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kunlik quvvat"
                    ),
                ),
                (
                    "lead_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Tayyorlash muddati (kun)"
                    ),
                ),
                (
                    "delivery",
                    models.BooleanField(
                        default=True, verbose_name="Yetkazib berish bor"
                    ),
                ),
                (
                    "address",
                    models.JSONField(
                        blank=True,
                        default=market.models.i18n_default,
                        verbose_name="Ishlab chiqarilgan manzil",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ichki izoh"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("search", models.TextField(blank=True, editable=False)),
                ("views", models.PositiveIntegerField(default=0)),
                ("sold", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="market.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="market.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.JSONField(default=market.models.i18n_default)),
                ("spec", models.JSONField(default=market.models.i18n_default)),
                ("unit", models.CharField(max_length=16)),
                ("qty", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.application",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(default="uz", max_length=8)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="market.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                ("text", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="market.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
