# Generated by Django 5.2.17 on 2026-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_is_sample",
            field=models.BooleanField(
                default=False,
                help_text="Haqiqiy surat yuklanganda avtomatik o'chadi",
                verbose_name="Namunaviy (AI) rasm",
            ),
        ),
    ]
